### ISSUE TITLE
Erreur fichier/dossier non existant

### ISSUE THREAD

**Issue by JulienCoutault** [VictorJosso/Messagerie#2]
Bonjour, 

Le script Serveur.py (pourquoi mettre une majuscule ?) plante lorsque les fichiers ou dossiers de base  n'existent pas.

Jai eu le probleme pour 
- clients/Backup (dossier) --- Pourquoi une majuscule ?
- clients/convert-tables/mails (fichier)
- clients/convert-tables/users (fichier)
- clients/data (dossier)
- clients/groups (dossier)
- clients/Keys (dossier) --- Pareil, pourquoi une majuscule ?
- clients/messages (dossier)

Pour les fichiers un changement d'option d'ouverture suffit : juste ajouter un '+' ('r' +>  'r+') si je me souviens bien
Et pour les fichiers, tester  leur existence avec `os.path.exists()` et si besion les creer avec `os.makedirs()`

**Comment by VictorJosso** [comment]
Bonsoir, 

Alors en fait j'ai choisi de retirer le dossier "clients" de github parce que je jugeais cela "sensible". Il faut donc pour le moment créer soi-même l'arbo

**Comment by VictorJosso** [comment]
Suite du message :

L'arborescence pour le fonctionnement du serveur et enregistrer avec pickle un dictionnaire dans le fichier clients/convert-tables/users_ids. Le dossier est néanmoins toujours accessible via le premier commit si besoin. Je vais créer un script pour initialiser automatiquement tout ça dans la soirée.

**Comment by VictorJosso** [comment]
@JulienCoutault
Bonsoir,

Alors en fait j'ai choisi de retirer le dossier "clients" de github parce que je jugeais cela "sensible". Il faut donc pour le moment créer soi-même l'arborescence pour le fonctionnement du serveur et enregistrer avec pickle un dictionnaire dans le fichier clients/convert-tables/users_ids. Le dossier est néanmoins toujours accessible via les premiers commits si besoin. Je vais créer un script pour initialiser automatiquement tout ça dans la soirée.

**Comment by JulienCoutault** [comment]
Effectivement, il ne faut pas tracker ces dossiers (creer un gitignore pourrait etre interressant).
Le probleme d'un script d'initialisation est (qu'en plus de rajouter une etape lors de l'installation) qu'il ne resout pas le cas ou le fichier est supprimer apres l'installation (par un rm foireux par example).
C'est pour ca que je te conseille plutot de verifier, et de creer si besion, ces fichiers lors de l'execution normale du programme.

**Comment by VictorJosso** [comment]
Oui effectivement je m'y attelle tout de suite !

**Comment by VictorJosso** [comment]
@JulienCoutault 
Done ! Les dossiers sont créés automatiquement lorsqu'ils sont demandés par le serveur.

**Comment by JulienCoutault** [comment]
Tu as un probleme d'indentation a la ligne 27 (il manque un tab)

**Comment by VictorJosso** [comment]
@JulienCoutault 
Non non j'ai simplement supprimé la ligne sans faire attention : j'avais un `print` pour voir à chaque fois que les dossiers étaient ignorés, et lorsque j'ai supprimé le `print` j'ai oublié de remettre le `pass`

**Comment by JulienCoutault** [comment]
Ah oui, j'ai lu trop rapidement, le chdir ne doit pas etre dans l'exception
Laisser une exception vide est une mauvaise pratique : s'il y a une exception c'est que quelque chose ne s'est pas passer comme prevu. Dans ce cas, si tu n'arrives pas a creer un dossier, tu vas avoir du mal a te deplacer dedans.

Pense a controler qu'un dossier n'existe pas avant de le creer, le dossier 'toto/tata' peut ne pas exister alors que 'toto' existe. Ici pas besion de creer le dossier 'toto' (il me semble meme que `os.mkdir()` retourne une erreur)
Utilise `os.mknod()` plutot que de faire un appel systeme pour creer un fichier

**Comment by VictorJosso** [comment]
Oui en fait si le dossier existe alors `os.mkdir()` renvoie une erreur `OSError` : je sais donc que le dossier existe déjà et que je peux directement me placer dedans pour créer le sous-dossier suivant. J'ai fait ça parce-que la fonction `os.makedirs()`, qui créé des dossiers récursivement, retourne une erreur si l'un des dossiers parents existe déjà. Donc tout fonctionne. Tu en penses quoi ? Je vais me documenter sur `os.mknod()` parce-que je ne connais pas.

**Comment by VictorJosso** [comment]
Ok en fait `os.mknod(path)` fait la même chose que `os.system("touch "+path)`, c'est exactement ce qu'il me fallait parceque lorsque j'ai lancé mon serveur sur une machine Windows, forcément ça ne marchait pas... Bon en tout cas merci beaucoup !

**Comment by JulienCoutault** [comment]
Tu n'as pas push tes changements mais je ne vois pas ce que l'on pourrait faire d'autre (sur ce sujet)

EDIT : 
> j'ai lancé mon serveur sur une machine Windows, forcément ça ne marchait pas

C'est pour ca qu'il faut chercher des alternatives pour ne pas utiliser `os.system()` (sauf si la portabilité ne nous interesse vraiment pas)

**Comment by VictorJosso** [comment]
Les changements sont sur la branche Linux. Je vais migrer les deux je suis dessus.

En tout cas merci beaucoup ;)
